### ISSUE TITLE
Add embeds as custom post type

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#5]
Adding embeds as custom post type would also allow to add custom embed providers afterwards. It also would simplify #4 .

Required information for the custom post type can be found in https://git.aurora.ci/plugins/rh-goose (non-public).

- [x] Name
- [x] URL to the privacy policy of the service
- [x] Custom description for the overlay
- [x] Featured Image for the logo
- [x] Image for the background
- [x] Regex for classic editor
- [x] Regex for Gutenberg
- [x] Option to disable the embed provider (see #1, it shouldn’t do anything for the provider at all)

**To-do:**
- [x] Add auto-import of default providers
  - [x] On activation
  - [x] On update
- [x] Move main menu entry in the admin to the settings page as soon as settings exist (will be introduced in #7)

**Comment by MatzeKitt** [comment]
This would automatically resolve #1

**Comment by MatzeKitt** [comment]
It looks like this right now in the admin:

<img width="1875" alt="Bildschirmfoto 2021-01-01 um 20 28 59" src="https://user-images.githubusercontent.com/1018979/103445067-ff1b6b80-4c6f-11eb-9cd2-7e0d6f44406f.png">
